name: Build & Deploy Quartz (Docker)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t familyhistories .

    - name: Run container and extract built site
      run: |
        docker create --name build-run familyhistories
        docker start -a build-run                   # 🚀 This actually runs the site generation
        mkdir -p site/public                        # Ensure local dir exists
        docker cp build-run:/app/site/public/. ./site/public
        docker rm build-run

    - name: Upload site to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: site/public



  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
    - id: deploy
      uses: actions/deploy-pages@v4
